### ISSUE TITLE
 Logout Functionality Not Working

### ISSUE THREAD

**Issue by anversa-pro** [CHUPITO-Org/FE-Chupito#38]
The logout functionality in the  application is currently non-functional. When attempting to log out, there is no response or confirmation, and the user's session persists. Additionally, the backend returns a 401 Unauthorized error.

**Steps to Reproduce:**

1. Log in to the Event Manager Frontend with valid credentials.
2. Navigate to any page within the application.
3. Attempt to log out by clicking the "Logout" button.

**Comment by jose-sal-y-rosas** [comment]
Solved in this PR: https://github.com/CHUPITO-Org/FE-Chupito/pull/53
